### ISSUE TITLE
I'm pretty sure you can deactivate any account with the /deactivate route. haha

### ISSUE THREAD

**Issue by brandongit2** [brandongit2/slate#4]

**Comment by mchlp** [comment]
Isn't this intended behaviour?

**Comment by brandongit2** [comment]
lol i really mean _any_ account. if i were just some random user i could go to `slate.brandontsang.net/deactivate?q=brandononline2@gmail.com` and my account would be deactivated

**Comment by brandongit2** [comment]
but it looks like i haven't implemented account deactivation or password reset yet. i'll add those as issues.

**Comment by mchlp** [comment]
https://github.com/brandongit2/slate/blob/d57ccb5f641f69d1b3a2172b7257e5387f2d11fe/backend/src/user.js#L81

the query is your random string that shouldn't be guessed though

**Comment by brandongit2** [comment]
oh right i forgot about that
